/*
 * Teamwork Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmv1

import (
	"encoding/json"
)

// InlineResponse20089 struct for InlineResponse20089
type InlineResponse20089 struct {
	STATUS *string `json:"STATUS,omitempty"`
	SearchResult *InlineResponse20089SearchResult `json:"searchResult,omitempty"`
}

// NewInlineResponse20089 instantiates a new InlineResponse20089 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20089() *InlineResponse20089 {
	this := InlineResponse20089{}
	return &this
}

// NewInlineResponse20089WithDefaults instantiates a new InlineResponse20089 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20089WithDefaults() *InlineResponse20089 {
	this := InlineResponse20089{}
	return &this
}

// GetSTATUS returns the STATUS field value if set, zero value otherwise.
func (o *InlineResponse20089) GetSTATUS() string {
	if o == nil || o.STATUS == nil {
		var ret string
		return ret
	}
	return *o.STATUS
}

// GetSTATUSOk returns a tuple with the STATUS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20089) GetSTATUSOk() (*string, bool) {
	if o == nil || o.STATUS == nil {
		return nil, false
	}
	return o.STATUS, true
}

// HasSTATUS returns a boolean if a field has been set.
func (o *InlineResponse20089) HasSTATUS() bool {
	if o != nil && o.STATUS != nil {
		return true
	}

	return false
}

// SetSTATUS gets a reference to the given string and assigns it to the STATUS field.
func (o *InlineResponse20089) SetSTATUS(v string) {
	o.STATUS = &v
}

// GetSearchResult returns the SearchResult field value if set, zero value otherwise.
func (o *InlineResponse20089) GetSearchResult() InlineResponse20089SearchResult {
	if o == nil || o.SearchResult == nil {
		var ret InlineResponse20089SearchResult
		return ret
	}
	return *o.SearchResult
}

// GetSearchResultOk returns a tuple with the SearchResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20089) GetSearchResultOk() (*InlineResponse20089SearchResult, bool) {
	if o == nil || o.SearchResult == nil {
		return nil, false
	}
	return o.SearchResult, true
}

// HasSearchResult returns a boolean if a field has been set.
func (o *InlineResponse20089) HasSearchResult() bool {
	if o != nil && o.SearchResult != nil {
		return true
	}

	return false
}

// SetSearchResult gets a reference to the given InlineResponse20089SearchResult and assigns it to the SearchResult field.
func (o *InlineResponse20089) SetSearchResult(v InlineResponse20089SearchResult) {
	o.SearchResult = &v
}

func (o InlineResponse20089) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.STATUS != nil {
		toSerialize["STATUS"] = o.STATUS
	}
	if o.SearchResult != nil {
		toSerialize["searchResult"] = o.SearchResult
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20089 struct {
	value *InlineResponse20089
	isSet bool
}

func (v NullableInlineResponse20089) Get() *InlineResponse20089 {
	return v.value
}

func (v *NullableInlineResponse20089) Set(val *InlineResponse20089) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20089) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20089) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20089(val *InlineResponse20089) *NullableInlineResponse20089 {
	return &NullableInlineResponse20089{value: val, isSet: true}
}

func (v NullableInlineResponse20089) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20089) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


