/*
 * Teamwork Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmv1

import (
	"encoding/json"
)

// ProjectsIdFilesJsonFile struct for ProjectsIdFilesJsonFile
type ProjectsIdFilesJsonFile struct {
	CategoryId *string `json:"category-id,omitempty"`
	CategoryName *string `json:"category-name,omitempty"`
	Description *string `json:"description,omitempty"`
	Name *string `json:"name,omitempty"`
	Notify *string `json:"notify,omitempty"`
	PendingFileRef *string `json:"pendingFileRef,omitempty"`
	Private *string `json:"private,omitempty"`
	Tags *string `json:"tags,omitempty"`
}

// NewProjectsIdFilesJsonFile instantiates a new ProjectsIdFilesJsonFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectsIdFilesJsonFile() *ProjectsIdFilesJsonFile {
	this := ProjectsIdFilesJsonFile{}
	return &this
}

// NewProjectsIdFilesJsonFileWithDefaults instantiates a new ProjectsIdFilesJsonFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectsIdFilesJsonFileWithDefaults() *ProjectsIdFilesJsonFile {
	this := ProjectsIdFilesJsonFile{}
	return &this
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *ProjectsIdFilesJsonFile) GetCategoryId() string {
	if o == nil || o.CategoryId == nil {
		var ret string
		return ret
	}
	return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdFilesJsonFile) GetCategoryIdOk() (*string, bool) {
	if o == nil || o.CategoryId == nil {
		return nil, false
	}
	return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *ProjectsIdFilesJsonFile) HasCategoryId() bool {
	if o != nil && o.CategoryId != nil {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given string and assigns it to the CategoryId field.
func (o *ProjectsIdFilesJsonFile) SetCategoryId(v string) {
	o.CategoryId = &v
}

// GetCategoryName returns the CategoryName field value if set, zero value otherwise.
func (o *ProjectsIdFilesJsonFile) GetCategoryName() string {
	if o == nil || o.CategoryName == nil {
		var ret string
		return ret
	}
	return *o.CategoryName
}

// GetCategoryNameOk returns a tuple with the CategoryName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdFilesJsonFile) GetCategoryNameOk() (*string, bool) {
	if o == nil || o.CategoryName == nil {
		return nil, false
	}
	return o.CategoryName, true
}

// HasCategoryName returns a boolean if a field has been set.
func (o *ProjectsIdFilesJsonFile) HasCategoryName() bool {
	if o != nil && o.CategoryName != nil {
		return true
	}

	return false
}

// SetCategoryName gets a reference to the given string and assigns it to the CategoryName field.
func (o *ProjectsIdFilesJsonFile) SetCategoryName(v string) {
	o.CategoryName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProjectsIdFilesJsonFile) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdFilesJsonFile) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProjectsIdFilesJsonFile) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProjectsIdFilesJsonFile) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectsIdFilesJsonFile) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdFilesJsonFile) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectsIdFilesJsonFile) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectsIdFilesJsonFile) SetName(v string) {
	o.Name = &v
}

// GetNotify returns the Notify field value if set, zero value otherwise.
func (o *ProjectsIdFilesJsonFile) GetNotify() string {
	if o == nil || o.Notify == nil {
		var ret string
		return ret
	}
	return *o.Notify
}

// GetNotifyOk returns a tuple with the Notify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdFilesJsonFile) GetNotifyOk() (*string, bool) {
	if o == nil || o.Notify == nil {
		return nil, false
	}
	return o.Notify, true
}

// HasNotify returns a boolean if a field has been set.
func (o *ProjectsIdFilesJsonFile) HasNotify() bool {
	if o != nil && o.Notify != nil {
		return true
	}

	return false
}

// SetNotify gets a reference to the given string and assigns it to the Notify field.
func (o *ProjectsIdFilesJsonFile) SetNotify(v string) {
	o.Notify = &v
}

// GetPendingFileRef returns the PendingFileRef field value if set, zero value otherwise.
func (o *ProjectsIdFilesJsonFile) GetPendingFileRef() string {
	if o == nil || o.PendingFileRef == nil {
		var ret string
		return ret
	}
	return *o.PendingFileRef
}

// GetPendingFileRefOk returns a tuple with the PendingFileRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdFilesJsonFile) GetPendingFileRefOk() (*string, bool) {
	if o == nil || o.PendingFileRef == nil {
		return nil, false
	}
	return o.PendingFileRef, true
}

// HasPendingFileRef returns a boolean if a field has been set.
func (o *ProjectsIdFilesJsonFile) HasPendingFileRef() bool {
	if o != nil && o.PendingFileRef != nil {
		return true
	}

	return false
}

// SetPendingFileRef gets a reference to the given string and assigns it to the PendingFileRef field.
func (o *ProjectsIdFilesJsonFile) SetPendingFileRef(v string) {
	o.PendingFileRef = &v
}

// GetPrivate returns the Private field value if set, zero value otherwise.
func (o *ProjectsIdFilesJsonFile) GetPrivate() string {
	if o == nil || o.Private == nil {
		var ret string
		return ret
	}
	return *o.Private
}

// GetPrivateOk returns a tuple with the Private field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdFilesJsonFile) GetPrivateOk() (*string, bool) {
	if o == nil || o.Private == nil {
		return nil, false
	}
	return o.Private, true
}

// HasPrivate returns a boolean if a field has been set.
func (o *ProjectsIdFilesJsonFile) HasPrivate() bool {
	if o != nil && o.Private != nil {
		return true
	}

	return false
}

// SetPrivate gets a reference to the given string and assigns it to the Private field.
func (o *ProjectsIdFilesJsonFile) SetPrivate(v string) {
	o.Private = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ProjectsIdFilesJsonFile) GetTags() string {
	if o == nil || o.Tags == nil {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdFilesJsonFile) GetTagsOk() (*string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ProjectsIdFilesJsonFile) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *ProjectsIdFilesJsonFile) SetTags(v string) {
	o.Tags = &v
}

func (o ProjectsIdFilesJsonFile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CategoryId != nil {
		toSerialize["category-id"] = o.CategoryId
	}
	if o.CategoryName != nil {
		toSerialize["category-name"] = o.CategoryName
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Notify != nil {
		toSerialize["notify"] = o.Notify
	}
	if o.PendingFileRef != nil {
		toSerialize["pendingFileRef"] = o.PendingFileRef
	}
	if o.Private != nil {
		toSerialize["private"] = o.Private
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return json.Marshal(toSerialize)
}

type NullableProjectsIdFilesJsonFile struct {
	value *ProjectsIdFilesJsonFile
	isSet bool
}

func (v NullableProjectsIdFilesJsonFile) Get() *ProjectsIdFilesJsonFile {
	return v.value
}

func (v *NullableProjectsIdFilesJsonFile) Set(val *ProjectsIdFilesJsonFile) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectsIdFilesJsonFile) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectsIdFilesJsonFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectsIdFilesJsonFile(val *ProjectsIdFilesJsonFile) *NullableProjectsIdFilesJsonFile {
	return &NullableProjectsIdFilesJsonFile{value: val, isSet: true}
}

func (v NullableProjectsIdFilesJsonFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectsIdFilesJsonFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


