/*
 * Teamwork Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmv1

import (
	"encoding/json"
)

// InlineResponse20028UserStatus struct for InlineResponse20028UserStatus
type InlineResponse20028UserStatus struct {
	AvatarUrl *string `json:"avatar-url,omitempty"`
	FirstName *string `json:"first-name,omitempty"`
	Id *string `json:"id,omitempty"`
	LastName *string `json:"last-name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewInlineResponse20028UserStatus instantiates a new InlineResponse20028UserStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20028UserStatus() *InlineResponse20028UserStatus {
	this := InlineResponse20028UserStatus{}
	return &this
}

// NewInlineResponse20028UserStatusWithDefaults instantiates a new InlineResponse20028UserStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20028UserStatusWithDefaults() *InlineResponse20028UserStatus {
	this := InlineResponse20028UserStatus{}
	return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *InlineResponse20028UserStatus) GetAvatarUrl() string {
	if o == nil || o.AvatarUrl == nil {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20028UserStatus) GetAvatarUrlOk() (*string, bool) {
	if o == nil || o.AvatarUrl == nil {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *InlineResponse20028UserStatus) HasAvatarUrl() bool {
	if o != nil && o.AvatarUrl != nil {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *InlineResponse20028UserStatus) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *InlineResponse20028UserStatus) GetFirstName() string {
	if o == nil || o.FirstName == nil {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20028UserStatus) GetFirstNameOk() (*string, bool) {
	if o == nil || o.FirstName == nil {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *InlineResponse20028UserStatus) HasFirstName() bool {
	if o != nil && o.FirstName != nil {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *InlineResponse20028UserStatus) SetFirstName(v string) {
	o.FirstName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InlineResponse20028UserStatus) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20028UserStatus) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InlineResponse20028UserStatus) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InlineResponse20028UserStatus) SetId(v string) {
	o.Id = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *InlineResponse20028UserStatus) GetLastName() string {
	if o == nil || o.LastName == nil {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20028UserStatus) GetLastNameOk() (*string, bool) {
	if o == nil || o.LastName == nil {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *InlineResponse20028UserStatus) HasLastName() bool {
	if o != nil && o.LastName != nil {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *InlineResponse20028UserStatus) SetLastName(v string) {
	o.LastName = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InlineResponse20028UserStatus) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20028UserStatus) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InlineResponse20028UserStatus) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *InlineResponse20028UserStatus) SetStatus(v string) {
	o.Status = &v
}

func (o InlineResponse20028UserStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AvatarUrl != nil {
		toSerialize["avatar-url"] = o.AvatarUrl
	}
	if o.FirstName != nil {
		toSerialize["first-name"] = o.FirstName
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.LastName != nil {
		toSerialize["last-name"] = o.LastName
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20028UserStatus struct {
	value *InlineResponse20028UserStatus
	isSet bool
}

func (v NullableInlineResponse20028UserStatus) Get() *InlineResponse20028UserStatus {
	return v.value
}

func (v *NullableInlineResponse20028UserStatus) Set(val *InlineResponse20028UserStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20028UserStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20028UserStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20028UserStatus(val *InlineResponse20028UserStatus) *NullableInlineResponse20028UserStatus {
	return &NullableInlineResponse20028UserStatus{value: val, isSet: true}
}

func (v NullableInlineResponse20028UserStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20028UserStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


