/*
 * Teamwork Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmv1

import (
	"encoding/json"
)

// ProjectsIdRatesJsonRatesUsers struct for ProjectsIdRatesJsonRatesUsers
type ProjectsIdRatesJsonRatesUsers struct {
	Var12345 *ProjectsIdRatesJsonRatesUsers12345 `json:"12345,omitempty"`
	Var12346 *ProjectsIdRatesJsonRatesUsers12345 `json:"12346,omitempty"`
}

// NewProjectsIdRatesJsonRatesUsers instantiates a new ProjectsIdRatesJsonRatesUsers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectsIdRatesJsonRatesUsers() *ProjectsIdRatesJsonRatesUsers {
	this := ProjectsIdRatesJsonRatesUsers{}
	return &this
}

// NewProjectsIdRatesJsonRatesUsersWithDefaults instantiates a new ProjectsIdRatesJsonRatesUsers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectsIdRatesJsonRatesUsersWithDefaults() *ProjectsIdRatesJsonRatesUsers {
	this := ProjectsIdRatesJsonRatesUsers{}
	return &this
}

// GetVar12345 returns the Var12345 field value if set, zero value otherwise.
func (o *ProjectsIdRatesJsonRatesUsers) GetVar12345() ProjectsIdRatesJsonRatesUsers12345 {
	if o == nil || o.Var12345 == nil {
		var ret ProjectsIdRatesJsonRatesUsers12345
		return ret
	}
	return *o.Var12345
}

// GetVar12345Ok returns a tuple with the Var12345 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdRatesJsonRatesUsers) GetVar12345Ok() (*ProjectsIdRatesJsonRatesUsers12345, bool) {
	if o == nil || o.Var12345 == nil {
		return nil, false
	}
	return o.Var12345, true
}

// HasVar12345 returns a boolean if a field has been set.
func (o *ProjectsIdRatesJsonRatesUsers) HasVar12345() bool {
	if o != nil && o.Var12345 != nil {
		return true
	}

	return false
}

// SetVar12345 gets a reference to the given ProjectsIdRatesJsonRatesUsers12345 and assigns it to the Var12345 field.
func (o *ProjectsIdRatesJsonRatesUsers) SetVar12345(v ProjectsIdRatesJsonRatesUsers12345) {
	o.Var12345 = &v
}

// GetVar12346 returns the Var12346 field value if set, zero value otherwise.
func (o *ProjectsIdRatesJsonRatesUsers) GetVar12346() ProjectsIdRatesJsonRatesUsers12345 {
	if o == nil || o.Var12346 == nil {
		var ret ProjectsIdRatesJsonRatesUsers12345
		return ret
	}
	return *o.Var12346
}

// GetVar12346Ok returns a tuple with the Var12346 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectsIdRatesJsonRatesUsers) GetVar12346Ok() (*ProjectsIdRatesJsonRatesUsers12345, bool) {
	if o == nil || o.Var12346 == nil {
		return nil, false
	}
	return o.Var12346, true
}

// HasVar12346 returns a boolean if a field has been set.
func (o *ProjectsIdRatesJsonRatesUsers) HasVar12346() bool {
	if o != nil && o.Var12346 != nil {
		return true
	}

	return false
}

// SetVar12346 gets a reference to the given ProjectsIdRatesJsonRatesUsers12345 and assigns it to the Var12346 field.
func (o *ProjectsIdRatesJsonRatesUsers) SetVar12346(v ProjectsIdRatesJsonRatesUsers12345) {
	o.Var12346 = &v
}

func (o ProjectsIdRatesJsonRatesUsers) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Var12345 != nil {
		toSerialize["12345"] = o.Var12345
	}
	if o.Var12346 != nil {
		toSerialize["12346"] = o.Var12346
	}
	return json.Marshal(toSerialize)
}

type NullableProjectsIdRatesJsonRatesUsers struct {
	value *ProjectsIdRatesJsonRatesUsers
	isSet bool
}

func (v NullableProjectsIdRatesJsonRatesUsers) Get() *ProjectsIdRatesJsonRatesUsers {
	return v.value
}

func (v *NullableProjectsIdRatesJsonRatesUsers) Set(val *ProjectsIdRatesJsonRatesUsers) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectsIdRatesJsonRatesUsers) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectsIdRatesJsonRatesUsers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectsIdRatesJsonRatesUsers(val *ProjectsIdRatesJsonRatesUsers) *NullableProjectsIdRatesJsonRatesUsers {
	return &NullableProjectsIdRatesJsonRatesUsers{value: val, isSet: true}
}

func (v NullableProjectsIdRatesJsonRatesUsers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectsIdRatesJsonRatesUsers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


