/*
 * Teamwork Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmv1

import (
	"encoding/json"
)

// InlineObject92 struct for InlineObject92
type InlineObject92 struct {
	TodoItems *[]TasklistsIdTasksReorderJsonTodoItems `json:"todo-items,omitempty"`
}

// NewInlineObject92 instantiates a new InlineObject92 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject92() *InlineObject92 {
	this := InlineObject92{}
	return &this
}

// NewInlineObject92WithDefaults instantiates a new InlineObject92 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject92WithDefaults() *InlineObject92 {
	this := InlineObject92{}
	return &this
}

// GetTodoItems returns the TodoItems field value if set, zero value otherwise.
func (o *InlineObject92) GetTodoItems() []TasklistsIdTasksReorderJsonTodoItems {
	if o == nil || o.TodoItems == nil {
		var ret []TasklistsIdTasksReorderJsonTodoItems
		return ret
	}
	return *o.TodoItems
}

// GetTodoItemsOk returns a tuple with the TodoItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject92) GetTodoItemsOk() (*[]TasklistsIdTasksReorderJsonTodoItems, bool) {
	if o == nil || o.TodoItems == nil {
		return nil, false
	}
	return o.TodoItems, true
}

// HasTodoItems returns a boolean if a field has been set.
func (o *InlineObject92) HasTodoItems() bool {
	if o != nil && o.TodoItems != nil {
		return true
	}

	return false
}

// SetTodoItems gets a reference to the given []TasklistsIdTasksReorderJsonTodoItems and assigns it to the TodoItems field.
func (o *InlineObject92) SetTodoItems(v []TasklistsIdTasksReorderJsonTodoItems) {
	o.TodoItems = &v
}

func (o InlineObject92) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TodoItems != nil {
		toSerialize["todo-items"] = o.TodoItems
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject92 struct {
	value *InlineObject92
	isSet bool
}

func (v NullableInlineObject92) Get() *InlineObject92 {
	return v.value
}

func (v *NullableInlineObject92) Set(val *InlineObject92) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject92) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject92) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject92(val *InlineObject92) *NullableInlineObject92 {
	return &NullableInlineObject92{value: val, isSet: true}
}

func (v NullableInlineObject92) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject92) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


