/*
 * Teamwork Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmv1

import (
	"encoding/json"
)

// InlineResponse200100TodoItem struct for InlineResponse200100TodoItem
type InlineResponse200100TodoItem struct {
	DLM *int32 `json:"DLM,omitempty"`
	AttachmentsCount *int32 `json:"attachments-count,omitempty"`
	BoardColumn *InlineResponse20054Category `json:"boardColumn,omitempty"`
	CanComplete *bool `json:"canComplete,omitempty"`
	CanEdit *bool `json:"canEdit,omitempty"`
	CanLogTime *bool `json:"canLogTime,omitempty"`
	CommentsCount *int32 `json:"comments-count,omitempty"`
	CompanyId *int32 `json:"company-id,omitempty"`
	CompanyName *string `json:"company-name,omitempty"`
	Completed *bool `json:"completed,omitempty"`
	Content *string `json:"content,omitempty"`
	CreatedOn *string `json:"created-on,omitempty"`
	CreatorAvatarUrl *string `json:"creator-avatar-url,omitempty"`
	CreatorFirstname *string `json:"creator-firstname,omitempty"`
	CreatorId *int32 `json:"creator-id,omitempty"`
	CreatorLastname *string `json:"creator-lastname,omitempty"`
	Description *string `json:"description,omitempty"`
	// If a task due date is defined, it will be returned in this field matching due date base. If there is no task due date set, but a milestone is assoicated, it will return the milestone due date.
	DueDate *string `json:"due-date,omitempty"`
	// If the task has a defined due date, this will be set. Otherwise, it will be empty.
	DueDateBase *string `json:"due-date-base,omitempty"`
	EstimatedMinutes *int32 `json:"estimated-minutes,omitempty"`
	HarvestEnabled *bool `json:"harvest-enabled,omitempty"`
	HasDependencies *int32 `json:"has-dependencies,omitempty"`
	HasReminders *bool `json:"has-reminders,omitempty"`
	HasUnreadComments *bool `json:"has-unread-comments,omitempty"`
	HasTickets *bool `json:"hasTickets,omitempty"`
	Id *int32 `json:"id,omitempty"`
	LastChangedOn *string `json:"last-changed-on,omitempty"`
	LockdownId *string `json:"lockdownId,omitempty"`
	Order *int32 `json:"order,omitempty"`
	ParentTaskId *string `json:"parentTaskId,omitempty"`
	Position *int32 `json:"position,omitempty"`
	Predecessors *[]map[string]interface{} `json:"predecessors,omitempty"`
	Priority *string `json:"priority,omitempty"`
	Private *int32 `json:"private,omitempty"`
	Progress *int32 `json:"progress,omitempty"`
	ProjectId *int32 `json:"project-id,omitempty"`
	ProjectName *string `json:"project-name,omitempty"`
	StartDate *string `json:"start-date,omitempty"`
	Status *string `json:"status,omitempty"`
	TasklistIsTemplate *bool `json:"tasklist-isTemplate,omitempty"`
	TasklistLockdownId *string `json:"tasklist-lockdownId,omitempty"`
	TasklistPrivate *bool `json:"tasklist-private,omitempty"`
	TimeIsLogged *string `json:"timeIsLogged,omitempty"`
	TodoListId *int32 `json:"todo-list-id,omitempty"`
	TodoListName *string `json:"todo-list-name,omitempty"`
	UpdaterFirstname *string `json:"updater-firstname,omitempty"`
	UpdaterId *int32 `json:"updater-id,omitempty"`
	UpdaterLastname *string `json:"updater-lastname,omitempty"`
	UserFollowingChanges *bool `json:"userFollowingChanges,omitempty"`
	UserFollowingComments *bool `json:"userFollowingComments,omitempty"`
	ViewEstimatedTime *bool `json:"viewEstimatedTime,omitempty"`
}

// NewInlineResponse200100TodoItem instantiates a new InlineResponse200100TodoItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200100TodoItem() *InlineResponse200100TodoItem {
	this := InlineResponse200100TodoItem{}
	return &this
}

// NewInlineResponse200100TodoItemWithDefaults instantiates a new InlineResponse200100TodoItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200100TodoItemWithDefaults() *InlineResponse200100TodoItem {
	this := InlineResponse200100TodoItem{}
	return &this
}

// GetDLM returns the DLM field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetDLM() int32 {
	if o == nil || o.DLM == nil {
		var ret int32
		return ret
	}
	return *o.DLM
}

// GetDLMOk returns a tuple with the DLM field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetDLMOk() (*int32, bool) {
	if o == nil || o.DLM == nil {
		return nil, false
	}
	return o.DLM, true
}

// HasDLM returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasDLM() bool {
	if o != nil && o.DLM != nil {
		return true
	}

	return false
}

// SetDLM gets a reference to the given int32 and assigns it to the DLM field.
func (o *InlineResponse200100TodoItem) SetDLM(v int32) {
	o.DLM = &v
}

// GetAttachmentsCount returns the AttachmentsCount field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetAttachmentsCount() int32 {
	if o == nil || o.AttachmentsCount == nil {
		var ret int32
		return ret
	}
	return *o.AttachmentsCount
}

// GetAttachmentsCountOk returns a tuple with the AttachmentsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetAttachmentsCountOk() (*int32, bool) {
	if o == nil || o.AttachmentsCount == nil {
		return nil, false
	}
	return o.AttachmentsCount, true
}

// HasAttachmentsCount returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasAttachmentsCount() bool {
	if o != nil && o.AttachmentsCount != nil {
		return true
	}

	return false
}

// SetAttachmentsCount gets a reference to the given int32 and assigns it to the AttachmentsCount field.
func (o *InlineResponse200100TodoItem) SetAttachmentsCount(v int32) {
	o.AttachmentsCount = &v
}

// GetBoardColumn returns the BoardColumn field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetBoardColumn() InlineResponse20054Category {
	if o == nil || o.BoardColumn == nil {
		var ret InlineResponse20054Category
		return ret
	}
	return *o.BoardColumn
}

// GetBoardColumnOk returns a tuple with the BoardColumn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetBoardColumnOk() (*InlineResponse20054Category, bool) {
	if o == nil || o.BoardColumn == nil {
		return nil, false
	}
	return o.BoardColumn, true
}

// HasBoardColumn returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasBoardColumn() bool {
	if o != nil && o.BoardColumn != nil {
		return true
	}

	return false
}

// SetBoardColumn gets a reference to the given InlineResponse20054Category and assigns it to the BoardColumn field.
func (o *InlineResponse200100TodoItem) SetBoardColumn(v InlineResponse20054Category) {
	o.BoardColumn = &v
}

// GetCanComplete returns the CanComplete field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCanComplete() bool {
	if o == nil || o.CanComplete == nil {
		var ret bool
		return ret
	}
	return *o.CanComplete
}

// GetCanCompleteOk returns a tuple with the CanComplete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCanCompleteOk() (*bool, bool) {
	if o == nil || o.CanComplete == nil {
		return nil, false
	}
	return o.CanComplete, true
}

// HasCanComplete returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCanComplete() bool {
	if o != nil && o.CanComplete != nil {
		return true
	}

	return false
}

// SetCanComplete gets a reference to the given bool and assigns it to the CanComplete field.
func (o *InlineResponse200100TodoItem) SetCanComplete(v bool) {
	o.CanComplete = &v
}

// GetCanEdit returns the CanEdit field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCanEdit() bool {
	if o == nil || o.CanEdit == nil {
		var ret bool
		return ret
	}
	return *o.CanEdit
}

// GetCanEditOk returns a tuple with the CanEdit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCanEditOk() (*bool, bool) {
	if o == nil || o.CanEdit == nil {
		return nil, false
	}
	return o.CanEdit, true
}

// HasCanEdit returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCanEdit() bool {
	if o != nil && o.CanEdit != nil {
		return true
	}

	return false
}

// SetCanEdit gets a reference to the given bool and assigns it to the CanEdit field.
func (o *InlineResponse200100TodoItem) SetCanEdit(v bool) {
	o.CanEdit = &v
}

// GetCanLogTime returns the CanLogTime field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCanLogTime() bool {
	if o == nil || o.CanLogTime == nil {
		var ret bool
		return ret
	}
	return *o.CanLogTime
}

// GetCanLogTimeOk returns a tuple with the CanLogTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCanLogTimeOk() (*bool, bool) {
	if o == nil || o.CanLogTime == nil {
		return nil, false
	}
	return o.CanLogTime, true
}

// HasCanLogTime returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCanLogTime() bool {
	if o != nil && o.CanLogTime != nil {
		return true
	}

	return false
}

// SetCanLogTime gets a reference to the given bool and assigns it to the CanLogTime field.
func (o *InlineResponse200100TodoItem) SetCanLogTime(v bool) {
	o.CanLogTime = &v
}

// GetCommentsCount returns the CommentsCount field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCommentsCount() int32 {
	if o == nil || o.CommentsCount == nil {
		var ret int32
		return ret
	}
	return *o.CommentsCount
}

// GetCommentsCountOk returns a tuple with the CommentsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCommentsCountOk() (*int32, bool) {
	if o == nil || o.CommentsCount == nil {
		return nil, false
	}
	return o.CommentsCount, true
}

// HasCommentsCount returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCommentsCount() bool {
	if o != nil && o.CommentsCount != nil {
		return true
	}

	return false
}

// SetCommentsCount gets a reference to the given int32 and assigns it to the CommentsCount field.
func (o *InlineResponse200100TodoItem) SetCommentsCount(v int32) {
	o.CommentsCount = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCompanyId() int32 {
	if o == nil || o.CompanyId == nil {
		var ret int32
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCompanyIdOk() (*int32, bool) {
	if o == nil || o.CompanyId == nil {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCompanyId() bool {
	if o != nil && o.CompanyId != nil {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given int32 and assigns it to the CompanyId field.
func (o *InlineResponse200100TodoItem) SetCompanyId(v int32) {
	o.CompanyId = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCompanyName() string {
	if o == nil || o.CompanyName == nil {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCompanyNameOk() (*string, bool) {
	if o == nil || o.CompanyName == nil {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCompanyName() bool {
	if o != nil && o.CompanyName != nil {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *InlineResponse200100TodoItem) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetCompleted returns the Completed field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCompleted() bool {
	if o == nil || o.Completed == nil {
		var ret bool
		return ret
	}
	return *o.Completed
}

// GetCompletedOk returns a tuple with the Completed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCompletedOk() (*bool, bool) {
	if o == nil || o.Completed == nil {
		return nil, false
	}
	return o.Completed, true
}

// HasCompleted returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCompleted() bool {
	if o != nil && o.Completed != nil {
		return true
	}

	return false
}

// SetCompleted gets a reference to the given bool and assigns it to the Completed field.
func (o *InlineResponse200100TodoItem) SetCompleted(v bool) {
	o.Completed = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetContent() string {
	if o == nil || o.Content == nil {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetContentOk() (*string, bool) {
	if o == nil || o.Content == nil {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasContent() bool {
	if o != nil && o.Content != nil {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *InlineResponse200100TodoItem) SetContent(v string) {
	o.Content = &v
}

// GetCreatedOn returns the CreatedOn field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCreatedOn() string {
	if o == nil || o.CreatedOn == nil {
		var ret string
		return ret
	}
	return *o.CreatedOn
}

// GetCreatedOnOk returns a tuple with the CreatedOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCreatedOnOk() (*string, bool) {
	if o == nil || o.CreatedOn == nil {
		return nil, false
	}
	return o.CreatedOn, true
}

// HasCreatedOn returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCreatedOn() bool {
	if o != nil && o.CreatedOn != nil {
		return true
	}

	return false
}

// SetCreatedOn gets a reference to the given string and assigns it to the CreatedOn field.
func (o *InlineResponse200100TodoItem) SetCreatedOn(v string) {
	o.CreatedOn = &v
}

// GetCreatorAvatarUrl returns the CreatorAvatarUrl field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCreatorAvatarUrl() string {
	if o == nil || o.CreatorAvatarUrl == nil {
		var ret string
		return ret
	}
	return *o.CreatorAvatarUrl
}

// GetCreatorAvatarUrlOk returns a tuple with the CreatorAvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCreatorAvatarUrlOk() (*string, bool) {
	if o == nil || o.CreatorAvatarUrl == nil {
		return nil, false
	}
	return o.CreatorAvatarUrl, true
}

// HasCreatorAvatarUrl returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCreatorAvatarUrl() bool {
	if o != nil && o.CreatorAvatarUrl != nil {
		return true
	}

	return false
}

// SetCreatorAvatarUrl gets a reference to the given string and assigns it to the CreatorAvatarUrl field.
func (o *InlineResponse200100TodoItem) SetCreatorAvatarUrl(v string) {
	o.CreatorAvatarUrl = &v
}

// GetCreatorFirstname returns the CreatorFirstname field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCreatorFirstname() string {
	if o == nil || o.CreatorFirstname == nil {
		var ret string
		return ret
	}
	return *o.CreatorFirstname
}

// GetCreatorFirstnameOk returns a tuple with the CreatorFirstname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCreatorFirstnameOk() (*string, bool) {
	if o == nil || o.CreatorFirstname == nil {
		return nil, false
	}
	return o.CreatorFirstname, true
}

// HasCreatorFirstname returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCreatorFirstname() bool {
	if o != nil && o.CreatorFirstname != nil {
		return true
	}

	return false
}

// SetCreatorFirstname gets a reference to the given string and assigns it to the CreatorFirstname field.
func (o *InlineResponse200100TodoItem) SetCreatorFirstname(v string) {
	o.CreatorFirstname = &v
}

// GetCreatorId returns the CreatorId field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCreatorId() int32 {
	if o == nil || o.CreatorId == nil {
		var ret int32
		return ret
	}
	return *o.CreatorId
}

// GetCreatorIdOk returns a tuple with the CreatorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCreatorIdOk() (*int32, bool) {
	if o == nil || o.CreatorId == nil {
		return nil, false
	}
	return o.CreatorId, true
}

// HasCreatorId returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCreatorId() bool {
	if o != nil && o.CreatorId != nil {
		return true
	}

	return false
}

// SetCreatorId gets a reference to the given int32 and assigns it to the CreatorId field.
func (o *InlineResponse200100TodoItem) SetCreatorId(v int32) {
	o.CreatorId = &v
}

// GetCreatorLastname returns the CreatorLastname field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetCreatorLastname() string {
	if o == nil || o.CreatorLastname == nil {
		var ret string
		return ret
	}
	return *o.CreatorLastname
}

// GetCreatorLastnameOk returns a tuple with the CreatorLastname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetCreatorLastnameOk() (*string, bool) {
	if o == nil || o.CreatorLastname == nil {
		return nil, false
	}
	return o.CreatorLastname, true
}

// HasCreatorLastname returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasCreatorLastname() bool {
	if o != nil && o.CreatorLastname != nil {
		return true
	}

	return false
}

// SetCreatorLastname gets a reference to the given string and assigns it to the CreatorLastname field.
func (o *InlineResponse200100TodoItem) SetCreatorLastname(v string) {
	o.CreatorLastname = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InlineResponse200100TodoItem) SetDescription(v string) {
	o.Description = &v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetDueDate() string {
	if o == nil || o.DueDate == nil {
		var ret string
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetDueDateOk() (*string, bool) {
	if o == nil || o.DueDate == nil {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasDueDate() bool {
	if o != nil && o.DueDate != nil {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given string and assigns it to the DueDate field.
func (o *InlineResponse200100TodoItem) SetDueDate(v string) {
	o.DueDate = &v
}

// GetDueDateBase returns the DueDateBase field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetDueDateBase() string {
	if o == nil || o.DueDateBase == nil {
		var ret string
		return ret
	}
	return *o.DueDateBase
}

// GetDueDateBaseOk returns a tuple with the DueDateBase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetDueDateBaseOk() (*string, bool) {
	if o == nil || o.DueDateBase == nil {
		return nil, false
	}
	return o.DueDateBase, true
}

// HasDueDateBase returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasDueDateBase() bool {
	if o != nil && o.DueDateBase != nil {
		return true
	}

	return false
}

// SetDueDateBase gets a reference to the given string and assigns it to the DueDateBase field.
func (o *InlineResponse200100TodoItem) SetDueDateBase(v string) {
	o.DueDateBase = &v
}

// GetEstimatedMinutes returns the EstimatedMinutes field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetEstimatedMinutes() int32 {
	if o == nil || o.EstimatedMinutes == nil {
		var ret int32
		return ret
	}
	return *o.EstimatedMinutes
}

// GetEstimatedMinutesOk returns a tuple with the EstimatedMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetEstimatedMinutesOk() (*int32, bool) {
	if o == nil || o.EstimatedMinutes == nil {
		return nil, false
	}
	return o.EstimatedMinutes, true
}

// HasEstimatedMinutes returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasEstimatedMinutes() bool {
	if o != nil && o.EstimatedMinutes != nil {
		return true
	}

	return false
}

// SetEstimatedMinutes gets a reference to the given int32 and assigns it to the EstimatedMinutes field.
func (o *InlineResponse200100TodoItem) SetEstimatedMinutes(v int32) {
	o.EstimatedMinutes = &v
}

// GetHarvestEnabled returns the HarvestEnabled field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetHarvestEnabled() bool {
	if o == nil || o.HarvestEnabled == nil {
		var ret bool
		return ret
	}
	return *o.HarvestEnabled
}

// GetHarvestEnabledOk returns a tuple with the HarvestEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetHarvestEnabledOk() (*bool, bool) {
	if o == nil || o.HarvestEnabled == nil {
		return nil, false
	}
	return o.HarvestEnabled, true
}

// HasHarvestEnabled returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasHarvestEnabled() bool {
	if o != nil && o.HarvestEnabled != nil {
		return true
	}

	return false
}

// SetHarvestEnabled gets a reference to the given bool and assigns it to the HarvestEnabled field.
func (o *InlineResponse200100TodoItem) SetHarvestEnabled(v bool) {
	o.HarvestEnabled = &v
}

// GetHasDependencies returns the HasDependencies field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetHasDependencies() int32 {
	if o == nil || o.HasDependencies == nil {
		var ret int32
		return ret
	}
	return *o.HasDependencies
}

// GetHasDependenciesOk returns a tuple with the HasDependencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetHasDependenciesOk() (*int32, bool) {
	if o == nil || o.HasDependencies == nil {
		return nil, false
	}
	return o.HasDependencies, true
}

// HasHasDependencies returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasHasDependencies() bool {
	if o != nil && o.HasDependencies != nil {
		return true
	}

	return false
}

// SetHasDependencies gets a reference to the given int32 and assigns it to the HasDependencies field.
func (o *InlineResponse200100TodoItem) SetHasDependencies(v int32) {
	o.HasDependencies = &v
}

// GetHasReminders returns the HasReminders field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetHasReminders() bool {
	if o == nil || o.HasReminders == nil {
		var ret bool
		return ret
	}
	return *o.HasReminders
}

// GetHasRemindersOk returns a tuple with the HasReminders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetHasRemindersOk() (*bool, bool) {
	if o == nil || o.HasReminders == nil {
		return nil, false
	}
	return o.HasReminders, true
}

// HasHasReminders returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasHasReminders() bool {
	if o != nil && o.HasReminders != nil {
		return true
	}

	return false
}

// SetHasReminders gets a reference to the given bool and assigns it to the HasReminders field.
func (o *InlineResponse200100TodoItem) SetHasReminders(v bool) {
	o.HasReminders = &v
}

// GetHasUnreadComments returns the HasUnreadComments field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetHasUnreadComments() bool {
	if o == nil || o.HasUnreadComments == nil {
		var ret bool
		return ret
	}
	return *o.HasUnreadComments
}

// GetHasUnreadCommentsOk returns a tuple with the HasUnreadComments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetHasUnreadCommentsOk() (*bool, bool) {
	if o == nil || o.HasUnreadComments == nil {
		return nil, false
	}
	return o.HasUnreadComments, true
}

// HasHasUnreadComments returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasHasUnreadComments() bool {
	if o != nil && o.HasUnreadComments != nil {
		return true
	}

	return false
}

// SetHasUnreadComments gets a reference to the given bool and assigns it to the HasUnreadComments field.
func (o *InlineResponse200100TodoItem) SetHasUnreadComments(v bool) {
	o.HasUnreadComments = &v
}

// GetHasTickets returns the HasTickets field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetHasTickets() bool {
	if o == nil || o.HasTickets == nil {
		var ret bool
		return ret
	}
	return *o.HasTickets
}

// GetHasTicketsOk returns a tuple with the HasTickets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetHasTicketsOk() (*bool, bool) {
	if o == nil || o.HasTickets == nil {
		return nil, false
	}
	return o.HasTickets, true
}

// HasHasTickets returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasHasTickets() bool {
	if o != nil && o.HasTickets != nil {
		return true
	}

	return false
}

// SetHasTickets gets a reference to the given bool and assigns it to the HasTickets field.
func (o *InlineResponse200100TodoItem) SetHasTickets(v bool) {
	o.HasTickets = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *InlineResponse200100TodoItem) SetId(v int32) {
	o.Id = &v
}

// GetLastChangedOn returns the LastChangedOn field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetLastChangedOn() string {
	if o == nil || o.LastChangedOn == nil {
		var ret string
		return ret
	}
	return *o.LastChangedOn
}

// GetLastChangedOnOk returns a tuple with the LastChangedOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetLastChangedOnOk() (*string, bool) {
	if o == nil || o.LastChangedOn == nil {
		return nil, false
	}
	return o.LastChangedOn, true
}

// HasLastChangedOn returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasLastChangedOn() bool {
	if o != nil && o.LastChangedOn != nil {
		return true
	}

	return false
}

// SetLastChangedOn gets a reference to the given string and assigns it to the LastChangedOn field.
func (o *InlineResponse200100TodoItem) SetLastChangedOn(v string) {
	o.LastChangedOn = &v
}

// GetLockdownId returns the LockdownId field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetLockdownId() string {
	if o == nil || o.LockdownId == nil {
		var ret string
		return ret
	}
	return *o.LockdownId
}

// GetLockdownIdOk returns a tuple with the LockdownId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetLockdownIdOk() (*string, bool) {
	if o == nil || o.LockdownId == nil {
		return nil, false
	}
	return o.LockdownId, true
}

// HasLockdownId returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasLockdownId() bool {
	if o != nil && o.LockdownId != nil {
		return true
	}

	return false
}

// SetLockdownId gets a reference to the given string and assigns it to the LockdownId field.
func (o *InlineResponse200100TodoItem) SetLockdownId(v string) {
	o.LockdownId = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetOrder() int32 {
	if o == nil || o.Order == nil {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetOrderOk() (*int32, bool) {
	if o == nil || o.Order == nil {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasOrder() bool {
	if o != nil && o.Order != nil {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *InlineResponse200100TodoItem) SetOrder(v int32) {
	o.Order = &v
}

// GetParentTaskId returns the ParentTaskId field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetParentTaskId() string {
	if o == nil || o.ParentTaskId == nil {
		var ret string
		return ret
	}
	return *o.ParentTaskId
}

// GetParentTaskIdOk returns a tuple with the ParentTaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetParentTaskIdOk() (*string, bool) {
	if o == nil || o.ParentTaskId == nil {
		return nil, false
	}
	return o.ParentTaskId, true
}

// HasParentTaskId returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasParentTaskId() bool {
	if o != nil && o.ParentTaskId != nil {
		return true
	}

	return false
}

// SetParentTaskId gets a reference to the given string and assigns it to the ParentTaskId field.
func (o *InlineResponse200100TodoItem) SetParentTaskId(v string) {
	o.ParentTaskId = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetPosition() int32 {
	if o == nil || o.Position == nil {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetPositionOk() (*int32, bool) {
	if o == nil || o.Position == nil {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasPosition() bool {
	if o != nil && o.Position != nil {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *InlineResponse200100TodoItem) SetPosition(v int32) {
	o.Position = &v
}

// GetPredecessors returns the Predecessors field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetPredecessors() []map[string]interface{} {
	if o == nil || o.Predecessors == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Predecessors
}

// GetPredecessorsOk returns a tuple with the Predecessors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetPredecessorsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Predecessors == nil {
		return nil, false
	}
	return o.Predecessors, true
}

// HasPredecessors returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasPredecessors() bool {
	if o != nil && o.Predecessors != nil {
		return true
	}

	return false
}

// SetPredecessors gets a reference to the given []map[string]interface{} and assigns it to the Predecessors field.
func (o *InlineResponse200100TodoItem) SetPredecessors(v []map[string]interface{}) {
	o.Predecessors = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetPriority() string {
	if o == nil || o.Priority == nil {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetPriorityOk() (*string, bool) {
	if o == nil || o.Priority == nil {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasPriority() bool {
	if o != nil && o.Priority != nil {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *InlineResponse200100TodoItem) SetPriority(v string) {
	o.Priority = &v
}

// GetPrivate returns the Private field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetPrivate() int32 {
	if o == nil || o.Private == nil {
		var ret int32
		return ret
	}
	return *o.Private
}

// GetPrivateOk returns a tuple with the Private field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetPrivateOk() (*int32, bool) {
	if o == nil || o.Private == nil {
		return nil, false
	}
	return o.Private, true
}

// HasPrivate returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasPrivate() bool {
	if o != nil && o.Private != nil {
		return true
	}

	return false
}

// SetPrivate gets a reference to the given int32 and assigns it to the Private field.
func (o *InlineResponse200100TodoItem) SetPrivate(v int32) {
	o.Private = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetProgress() int32 {
	if o == nil || o.Progress == nil {
		var ret int32
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetProgressOk() (*int32, bool) {
	if o == nil || o.Progress == nil {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasProgress() bool {
	if o != nil && o.Progress != nil {
		return true
	}

	return false
}

// SetProgress gets a reference to the given int32 and assigns it to the Progress field.
func (o *InlineResponse200100TodoItem) SetProgress(v int32) {
	o.Progress = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetProjectId() int32 {
	if o == nil || o.ProjectId == nil {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetProjectIdOk() (*int32, bool) {
	if o == nil || o.ProjectId == nil {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasProjectId() bool {
	if o != nil && o.ProjectId != nil {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *InlineResponse200100TodoItem) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetProjectName() string {
	if o == nil || o.ProjectName == nil {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetProjectNameOk() (*string, bool) {
	if o == nil || o.ProjectName == nil {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasProjectName() bool {
	if o != nil && o.ProjectName != nil {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *InlineResponse200100TodoItem) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetStartDate() string {
	if o == nil || o.StartDate == nil {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetStartDateOk() (*string, bool) {
	if o == nil || o.StartDate == nil {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasStartDate() bool {
	if o != nil && o.StartDate != nil {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *InlineResponse200100TodoItem) SetStartDate(v string) {
	o.StartDate = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *InlineResponse200100TodoItem) SetStatus(v string) {
	o.Status = &v
}

// GetTasklistIsTemplate returns the TasklistIsTemplate field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetTasklistIsTemplate() bool {
	if o == nil || o.TasklistIsTemplate == nil {
		var ret bool
		return ret
	}
	return *o.TasklistIsTemplate
}

// GetTasklistIsTemplateOk returns a tuple with the TasklistIsTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetTasklistIsTemplateOk() (*bool, bool) {
	if o == nil || o.TasklistIsTemplate == nil {
		return nil, false
	}
	return o.TasklistIsTemplate, true
}

// HasTasklistIsTemplate returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasTasklistIsTemplate() bool {
	if o != nil && o.TasklistIsTemplate != nil {
		return true
	}

	return false
}

// SetTasklistIsTemplate gets a reference to the given bool and assigns it to the TasklistIsTemplate field.
func (o *InlineResponse200100TodoItem) SetTasklistIsTemplate(v bool) {
	o.TasklistIsTemplate = &v
}

// GetTasklistLockdownId returns the TasklistLockdownId field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetTasklistLockdownId() string {
	if o == nil || o.TasklistLockdownId == nil {
		var ret string
		return ret
	}
	return *o.TasklistLockdownId
}

// GetTasklistLockdownIdOk returns a tuple with the TasklistLockdownId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetTasklistLockdownIdOk() (*string, bool) {
	if o == nil || o.TasklistLockdownId == nil {
		return nil, false
	}
	return o.TasklistLockdownId, true
}

// HasTasklistLockdownId returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasTasklistLockdownId() bool {
	if o != nil && o.TasklistLockdownId != nil {
		return true
	}

	return false
}

// SetTasklistLockdownId gets a reference to the given string and assigns it to the TasklistLockdownId field.
func (o *InlineResponse200100TodoItem) SetTasklistLockdownId(v string) {
	o.TasklistLockdownId = &v
}

// GetTasklistPrivate returns the TasklistPrivate field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetTasklistPrivate() bool {
	if o == nil || o.TasklistPrivate == nil {
		var ret bool
		return ret
	}
	return *o.TasklistPrivate
}

// GetTasklistPrivateOk returns a tuple with the TasklistPrivate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetTasklistPrivateOk() (*bool, bool) {
	if o == nil || o.TasklistPrivate == nil {
		return nil, false
	}
	return o.TasklistPrivate, true
}

// HasTasklistPrivate returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasTasklistPrivate() bool {
	if o != nil && o.TasklistPrivate != nil {
		return true
	}

	return false
}

// SetTasklistPrivate gets a reference to the given bool and assigns it to the TasklistPrivate field.
func (o *InlineResponse200100TodoItem) SetTasklistPrivate(v bool) {
	o.TasklistPrivate = &v
}

// GetTimeIsLogged returns the TimeIsLogged field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetTimeIsLogged() string {
	if o == nil || o.TimeIsLogged == nil {
		var ret string
		return ret
	}
	return *o.TimeIsLogged
}

// GetTimeIsLoggedOk returns a tuple with the TimeIsLogged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetTimeIsLoggedOk() (*string, bool) {
	if o == nil || o.TimeIsLogged == nil {
		return nil, false
	}
	return o.TimeIsLogged, true
}

// HasTimeIsLogged returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasTimeIsLogged() bool {
	if o != nil && o.TimeIsLogged != nil {
		return true
	}

	return false
}

// SetTimeIsLogged gets a reference to the given string and assigns it to the TimeIsLogged field.
func (o *InlineResponse200100TodoItem) SetTimeIsLogged(v string) {
	o.TimeIsLogged = &v
}

// GetTodoListId returns the TodoListId field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetTodoListId() int32 {
	if o == nil || o.TodoListId == nil {
		var ret int32
		return ret
	}
	return *o.TodoListId
}

// GetTodoListIdOk returns a tuple with the TodoListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetTodoListIdOk() (*int32, bool) {
	if o == nil || o.TodoListId == nil {
		return nil, false
	}
	return o.TodoListId, true
}

// HasTodoListId returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasTodoListId() bool {
	if o != nil && o.TodoListId != nil {
		return true
	}

	return false
}

// SetTodoListId gets a reference to the given int32 and assigns it to the TodoListId field.
func (o *InlineResponse200100TodoItem) SetTodoListId(v int32) {
	o.TodoListId = &v
}

// GetTodoListName returns the TodoListName field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetTodoListName() string {
	if o == nil || o.TodoListName == nil {
		var ret string
		return ret
	}
	return *o.TodoListName
}

// GetTodoListNameOk returns a tuple with the TodoListName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetTodoListNameOk() (*string, bool) {
	if o == nil || o.TodoListName == nil {
		return nil, false
	}
	return o.TodoListName, true
}

// HasTodoListName returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasTodoListName() bool {
	if o != nil && o.TodoListName != nil {
		return true
	}

	return false
}

// SetTodoListName gets a reference to the given string and assigns it to the TodoListName field.
func (o *InlineResponse200100TodoItem) SetTodoListName(v string) {
	o.TodoListName = &v
}

// GetUpdaterFirstname returns the UpdaterFirstname field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetUpdaterFirstname() string {
	if o == nil || o.UpdaterFirstname == nil {
		var ret string
		return ret
	}
	return *o.UpdaterFirstname
}

// GetUpdaterFirstnameOk returns a tuple with the UpdaterFirstname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetUpdaterFirstnameOk() (*string, bool) {
	if o == nil || o.UpdaterFirstname == nil {
		return nil, false
	}
	return o.UpdaterFirstname, true
}

// HasUpdaterFirstname returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasUpdaterFirstname() bool {
	if o != nil && o.UpdaterFirstname != nil {
		return true
	}

	return false
}

// SetUpdaterFirstname gets a reference to the given string and assigns it to the UpdaterFirstname field.
func (o *InlineResponse200100TodoItem) SetUpdaterFirstname(v string) {
	o.UpdaterFirstname = &v
}

// GetUpdaterId returns the UpdaterId field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetUpdaterId() int32 {
	if o == nil || o.UpdaterId == nil {
		var ret int32
		return ret
	}
	return *o.UpdaterId
}

// GetUpdaterIdOk returns a tuple with the UpdaterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetUpdaterIdOk() (*int32, bool) {
	if o == nil || o.UpdaterId == nil {
		return nil, false
	}
	return o.UpdaterId, true
}

// HasUpdaterId returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasUpdaterId() bool {
	if o != nil && o.UpdaterId != nil {
		return true
	}

	return false
}

// SetUpdaterId gets a reference to the given int32 and assigns it to the UpdaterId field.
func (o *InlineResponse200100TodoItem) SetUpdaterId(v int32) {
	o.UpdaterId = &v
}

// GetUpdaterLastname returns the UpdaterLastname field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetUpdaterLastname() string {
	if o == nil || o.UpdaterLastname == nil {
		var ret string
		return ret
	}
	return *o.UpdaterLastname
}

// GetUpdaterLastnameOk returns a tuple with the UpdaterLastname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetUpdaterLastnameOk() (*string, bool) {
	if o == nil || o.UpdaterLastname == nil {
		return nil, false
	}
	return o.UpdaterLastname, true
}

// HasUpdaterLastname returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasUpdaterLastname() bool {
	if o != nil && o.UpdaterLastname != nil {
		return true
	}

	return false
}

// SetUpdaterLastname gets a reference to the given string and assigns it to the UpdaterLastname field.
func (o *InlineResponse200100TodoItem) SetUpdaterLastname(v string) {
	o.UpdaterLastname = &v
}

// GetUserFollowingChanges returns the UserFollowingChanges field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetUserFollowingChanges() bool {
	if o == nil || o.UserFollowingChanges == nil {
		var ret bool
		return ret
	}
	return *o.UserFollowingChanges
}

// GetUserFollowingChangesOk returns a tuple with the UserFollowingChanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetUserFollowingChangesOk() (*bool, bool) {
	if o == nil || o.UserFollowingChanges == nil {
		return nil, false
	}
	return o.UserFollowingChanges, true
}

// HasUserFollowingChanges returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasUserFollowingChanges() bool {
	if o != nil && o.UserFollowingChanges != nil {
		return true
	}

	return false
}

// SetUserFollowingChanges gets a reference to the given bool and assigns it to the UserFollowingChanges field.
func (o *InlineResponse200100TodoItem) SetUserFollowingChanges(v bool) {
	o.UserFollowingChanges = &v
}

// GetUserFollowingComments returns the UserFollowingComments field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetUserFollowingComments() bool {
	if o == nil || o.UserFollowingComments == nil {
		var ret bool
		return ret
	}
	return *o.UserFollowingComments
}

// GetUserFollowingCommentsOk returns a tuple with the UserFollowingComments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetUserFollowingCommentsOk() (*bool, bool) {
	if o == nil || o.UserFollowingComments == nil {
		return nil, false
	}
	return o.UserFollowingComments, true
}

// HasUserFollowingComments returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasUserFollowingComments() bool {
	if o != nil && o.UserFollowingComments != nil {
		return true
	}

	return false
}

// SetUserFollowingComments gets a reference to the given bool and assigns it to the UserFollowingComments field.
func (o *InlineResponse200100TodoItem) SetUserFollowingComments(v bool) {
	o.UserFollowingComments = &v
}

// GetViewEstimatedTime returns the ViewEstimatedTime field value if set, zero value otherwise.
func (o *InlineResponse200100TodoItem) GetViewEstimatedTime() bool {
	if o == nil || o.ViewEstimatedTime == nil {
		var ret bool
		return ret
	}
	return *o.ViewEstimatedTime
}

// GetViewEstimatedTimeOk returns a tuple with the ViewEstimatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200100TodoItem) GetViewEstimatedTimeOk() (*bool, bool) {
	if o == nil || o.ViewEstimatedTime == nil {
		return nil, false
	}
	return o.ViewEstimatedTime, true
}

// HasViewEstimatedTime returns a boolean if a field has been set.
func (o *InlineResponse200100TodoItem) HasViewEstimatedTime() bool {
	if o != nil && o.ViewEstimatedTime != nil {
		return true
	}

	return false
}

// SetViewEstimatedTime gets a reference to the given bool and assigns it to the ViewEstimatedTime field.
func (o *InlineResponse200100TodoItem) SetViewEstimatedTime(v bool) {
	o.ViewEstimatedTime = &v
}

func (o InlineResponse200100TodoItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DLM != nil {
		toSerialize["DLM"] = o.DLM
	}
	if o.AttachmentsCount != nil {
		toSerialize["attachments-count"] = o.AttachmentsCount
	}
	if o.BoardColumn != nil {
		toSerialize["boardColumn"] = o.BoardColumn
	}
	if o.CanComplete != nil {
		toSerialize["canComplete"] = o.CanComplete
	}
	if o.CanEdit != nil {
		toSerialize["canEdit"] = o.CanEdit
	}
	if o.CanLogTime != nil {
		toSerialize["canLogTime"] = o.CanLogTime
	}
	if o.CommentsCount != nil {
		toSerialize["comments-count"] = o.CommentsCount
	}
	if o.CompanyId != nil {
		toSerialize["company-id"] = o.CompanyId
	}
	if o.CompanyName != nil {
		toSerialize["company-name"] = o.CompanyName
	}
	if o.Completed != nil {
		toSerialize["completed"] = o.Completed
	}
	if o.Content != nil {
		toSerialize["content"] = o.Content
	}
	if o.CreatedOn != nil {
		toSerialize["created-on"] = o.CreatedOn
	}
	if o.CreatorAvatarUrl != nil {
		toSerialize["creator-avatar-url"] = o.CreatorAvatarUrl
	}
	if o.CreatorFirstname != nil {
		toSerialize["creator-firstname"] = o.CreatorFirstname
	}
	if o.CreatorId != nil {
		toSerialize["creator-id"] = o.CreatorId
	}
	if o.CreatorLastname != nil {
		toSerialize["creator-lastname"] = o.CreatorLastname
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.DueDate != nil {
		toSerialize["due-date"] = o.DueDate
	}
	if o.DueDateBase != nil {
		toSerialize["due-date-base"] = o.DueDateBase
	}
	if o.EstimatedMinutes != nil {
		toSerialize["estimated-minutes"] = o.EstimatedMinutes
	}
	if o.HarvestEnabled != nil {
		toSerialize["harvest-enabled"] = o.HarvestEnabled
	}
	if o.HasDependencies != nil {
		toSerialize["has-dependencies"] = o.HasDependencies
	}
	if o.HasReminders != nil {
		toSerialize["has-reminders"] = o.HasReminders
	}
	if o.HasUnreadComments != nil {
		toSerialize["has-unread-comments"] = o.HasUnreadComments
	}
	if o.HasTickets != nil {
		toSerialize["hasTickets"] = o.HasTickets
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.LastChangedOn != nil {
		toSerialize["last-changed-on"] = o.LastChangedOn
	}
	if o.LockdownId != nil {
		toSerialize["lockdownId"] = o.LockdownId
	}
	if o.Order != nil {
		toSerialize["order"] = o.Order
	}
	if o.ParentTaskId != nil {
		toSerialize["parentTaskId"] = o.ParentTaskId
	}
	if o.Position != nil {
		toSerialize["position"] = o.Position
	}
	if o.Predecessors != nil {
		toSerialize["predecessors"] = o.Predecessors
	}
	if o.Priority != nil {
		toSerialize["priority"] = o.Priority
	}
	if o.Private != nil {
		toSerialize["private"] = o.Private
	}
	if o.Progress != nil {
		toSerialize["progress"] = o.Progress
	}
	if o.ProjectId != nil {
		toSerialize["project-id"] = o.ProjectId
	}
	if o.ProjectName != nil {
		toSerialize["project-name"] = o.ProjectName
	}
	if o.StartDate != nil {
		toSerialize["start-date"] = o.StartDate
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.TasklistIsTemplate != nil {
		toSerialize["tasklist-isTemplate"] = o.TasklistIsTemplate
	}
	if o.TasklistLockdownId != nil {
		toSerialize["tasklist-lockdownId"] = o.TasklistLockdownId
	}
	if o.TasklistPrivate != nil {
		toSerialize["tasklist-private"] = o.TasklistPrivate
	}
	if o.TimeIsLogged != nil {
		toSerialize["timeIsLogged"] = o.TimeIsLogged
	}
	if o.TodoListId != nil {
		toSerialize["todo-list-id"] = o.TodoListId
	}
	if o.TodoListName != nil {
		toSerialize["todo-list-name"] = o.TodoListName
	}
	if o.UpdaterFirstname != nil {
		toSerialize["updater-firstname"] = o.UpdaterFirstname
	}
	if o.UpdaterId != nil {
		toSerialize["updater-id"] = o.UpdaterId
	}
	if o.UpdaterLastname != nil {
		toSerialize["updater-lastname"] = o.UpdaterLastname
	}
	if o.UserFollowingChanges != nil {
		toSerialize["userFollowingChanges"] = o.UserFollowingChanges
	}
	if o.UserFollowingComments != nil {
		toSerialize["userFollowingComments"] = o.UserFollowingComments
	}
	if o.ViewEstimatedTime != nil {
		toSerialize["viewEstimatedTime"] = o.ViewEstimatedTime
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200100TodoItem struct {
	value *InlineResponse200100TodoItem
	isSet bool
}

func (v NullableInlineResponse200100TodoItem) Get() *InlineResponse200100TodoItem {
	return v.value
}

func (v *NullableInlineResponse200100TodoItem) Set(val *InlineResponse200100TodoItem) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200100TodoItem) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200100TodoItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200100TodoItem(val *InlineResponse200100TodoItem) *NullableInlineResponse200100TodoItem {
	return &NullableInlineResponse200100TodoItem{value: val, isSet: true}
}

func (v NullableInlineResponse200100TodoItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200100TodoItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


