/*
 * Teamwork Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmv1

import (
	"encoding/json"
)

// InlineResponse20053Integrations struct for InlineResponse20053Integrations
type InlineResponse20053Integrations struct {
	MicrosoftConnectors *InlineResponse20039PersonIntegrationsMicrosoftConnector `json:"microsoftConnectors,omitempty"`
	Onedrivebusiness *InlineResponse20053IntegrationsOnedrivebusiness `json:"onedrivebusiness,omitempty"`
	Sharepoint *InlineResponse20053IntegrationsOnedrivebusiness `json:"sharepoint,omitempty"`
	Xero *InlineResponse20053IntegrationsXero `json:"xero,omitempty"`
}

// NewInlineResponse20053Integrations instantiates a new InlineResponse20053Integrations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20053Integrations() *InlineResponse20053Integrations {
	this := InlineResponse20053Integrations{}
	return &this
}

// NewInlineResponse20053IntegrationsWithDefaults instantiates a new InlineResponse20053Integrations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20053IntegrationsWithDefaults() *InlineResponse20053Integrations {
	this := InlineResponse20053Integrations{}
	return &this
}

// GetMicrosoftConnectors returns the MicrosoftConnectors field value if set, zero value otherwise.
func (o *InlineResponse20053Integrations) GetMicrosoftConnectors() InlineResponse20039PersonIntegrationsMicrosoftConnector {
	if o == nil || o.MicrosoftConnectors == nil {
		var ret InlineResponse20039PersonIntegrationsMicrosoftConnector
		return ret
	}
	return *o.MicrosoftConnectors
}

// GetMicrosoftConnectorsOk returns a tuple with the MicrosoftConnectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20053Integrations) GetMicrosoftConnectorsOk() (*InlineResponse20039PersonIntegrationsMicrosoftConnector, bool) {
	if o == nil || o.MicrosoftConnectors == nil {
		return nil, false
	}
	return o.MicrosoftConnectors, true
}

// HasMicrosoftConnectors returns a boolean if a field has been set.
func (o *InlineResponse20053Integrations) HasMicrosoftConnectors() bool {
	if o != nil && o.MicrosoftConnectors != nil {
		return true
	}

	return false
}

// SetMicrosoftConnectors gets a reference to the given InlineResponse20039PersonIntegrationsMicrosoftConnector and assigns it to the MicrosoftConnectors field.
func (o *InlineResponse20053Integrations) SetMicrosoftConnectors(v InlineResponse20039PersonIntegrationsMicrosoftConnector) {
	o.MicrosoftConnectors = &v
}

// GetOnedrivebusiness returns the Onedrivebusiness field value if set, zero value otherwise.
func (o *InlineResponse20053Integrations) GetOnedrivebusiness() InlineResponse20053IntegrationsOnedrivebusiness {
	if o == nil || o.Onedrivebusiness == nil {
		var ret InlineResponse20053IntegrationsOnedrivebusiness
		return ret
	}
	return *o.Onedrivebusiness
}

// GetOnedrivebusinessOk returns a tuple with the Onedrivebusiness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20053Integrations) GetOnedrivebusinessOk() (*InlineResponse20053IntegrationsOnedrivebusiness, bool) {
	if o == nil || o.Onedrivebusiness == nil {
		return nil, false
	}
	return o.Onedrivebusiness, true
}

// HasOnedrivebusiness returns a boolean if a field has been set.
func (o *InlineResponse20053Integrations) HasOnedrivebusiness() bool {
	if o != nil && o.Onedrivebusiness != nil {
		return true
	}

	return false
}

// SetOnedrivebusiness gets a reference to the given InlineResponse20053IntegrationsOnedrivebusiness and assigns it to the Onedrivebusiness field.
func (o *InlineResponse20053Integrations) SetOnedrivebusiness(v InlineResponse20053IntegrationsOnedrivebusiness) {
	o.Onedrivebusiness = &v
}

// GetSharepoint returns the Sharepoint field value if set, zero value otherwise.
func (o *InlineResponse20053Integrations) GetSharepoint() InlineResponse20053IntegrationsOnedrivebusiness {
	if o == nil || o.Sharepoint == nil {
		var ret InlineResponse20053IntegrationsOnedrivebusiness
		return ret
	}
	return *o.Sharepoint
}

// GetSharepointOk returns a tuple with the Sharepoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20053Integrations) GetSharepointOk() (*InlineResponse20053IntegrationsOnedrivebusiness, bool) {
	if o == nil || o.Sharepoint == nil {
		return nil, false
	}
	return o.Sharepoint, true
}

// HasSharepoint returns a boolean if a field has been set.
func (o *InlineResponse20053Integrations) HasSharepoint() bool {
	if o != nil && o.Sharepoint != nil {
		return true
	}

	return false
}

// SetSharepoint gets a reference to the given InlineResponse20053IntegrationsOnedrivebusiness and assigns it to the Sharepoint field.
func (o *InlineResponse20053Integrations) SetSharepoint(v InlineResponse20053IntegrationsOnedrivebusiness) {
	o.Sharepoint = &v
}

// GetXero returns the Xero field value if set, zero value otherwise.
func (o *InlineResponse20053Integrations) GetXero() InlineResponse20053IntegrationsXero {
	if o == nil || o.Xero == nil {
		var ret InlineResponse20053IntegrationsXero
		return ret
	}
	return *o.Xero
}

// GetXeroOk returns a tuple with the Xero field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20053Integrations) GetXeroOk() (*InlineResponse20053IntegrationsXero, bool) {
	if o == nil || o.Xero == nil {
		return nil, false
	}
	return o.Xero, true
}

// HasXero returns a boolean if a field has been set.
func (o *InlineResponse20053Integrations) HasXero() bool {
	if o != nil && o.Xero != nil {
		return true
	}

	return false
}

// SetXero gets a reference to the given InlineResponse20053IntegrationsXero and assigns it to the Xero field.
func (o *InlineResponse20053Integrations) SetXero(v InlineResponse20053IntegrationsXero) {
	o.Xero = &v
}

func (o InlineResponse20053Integrations) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MicrosoftConnectors != nil {
		toSerialize["microsoftConnectors"] = o.MicrosoftConnectors
	}
	if o.Onedrivebusiness != nil {
		toSerialize["onedrivebusiness"] = o.Onedrivebusiness
	}
	if o.Sharepoint != nil {
		toSerialize["sharepoint"] = o.Sharepoint
	}
	if o.Xero != nil {
		toSerialize["xero"] = o.Xero
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20053Integrations struct {
	value *InlineResponse20053Integrations
	isSet bool
}

func (v NullableInlineResponse20053Integrations) Get() *InlineResponse20053Integrations {
	return v.value
}

func (v *NullableInlineResponse20053Integrations) Set(val *InlineResponse20053Integrations) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20053Integrations) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20053Integrations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20053Integrations(val *InlineResponse20053Integrations) *NullableInlineResponse20053Integrations {
	return &NullableInlineResponse20053Integrations{value: val, isSet: true}
}

func (v NullableInlineResponse20053Integrations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20053Integrations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


