/*
 * Teamwork Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmv1

import (
	"encoding/json"
)

// InlineObject17 struct for InlineObject17
type InlineObject17 struct {
	STATUS *string `json:"STATUS,omitempty"`
	File *FilesIdJsonFile `json:"file,omitempty"`
}

// NewInlineObject17 instantiates a new InlineObject17 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject17() *InlineObject17 {
	this := InlineObject17{}
	return &this
}

// NewInlineObject17WithDefaults instantiates a new InlineObject17 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject17WithDefaults() *InlineObject17 {
	this := InlineObject17{}
	return &this
}

// GetSTATUS returns the STATUS field value if set, zero value otherwise.
func (o *InlineObject17) GetSTATUS() string {
	if o == nil || o.STATUS == nil {
		var ret string
		return ret
	}
	return *o.STATUS
}

// GetSTATUSOk returns a tuple with the STATUS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject17) GetSTATUSOk() (*string, bool) {
	if o == nil || o.STATUS == nil {
		return nil, false
	}
	return o.STATUS, true
}

// HasSTATUS returns a boolean if a field has been set.
func (o *InlineObject17) HasSTATUS() bool {
	if o != nil && o.STATUS != nil {
		return true
	}

	return false
}

// SetSTATUS gets a reference to the given string and assigns it to the STATUS field.
func (o *InlineObject17) SetSTATUS(v string) {
	o.STATUS = &v
}

// GetFile returns the File field value if set, zero value otherwise.
func (o *InlineObject17) GetFile() FilesIdJsonFile {
	if o == nil || o.File == nil {
		var ret FilesIdJsonFile
		return ret
	}
	return *o.File
}

// GetFileOk returns a tuple with the File field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject17) GetFileOk() (*FilesIdJsonFile, bool) {
	if o == nil || o.File == nil {
		return nil, false
	}
	return o.File, true
}

// HasFile returns a boolean if a field has been set.
func (o *InlineObject17) HasFile() bool {
	if o != nil && o.File != nil {
		return true
	}

	return false
}

// SetFile gets a reference to the given FilesIdJsonFile and assigns it to the File field.
func (o *InlineObject17) SetFile(v FilesIdJsonFile) {
	o.File = &v
}

func (o InlineObject17) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.STATUS != nil {
		toSerialize["STATUS"] = o.STATUS
	}
	if o.File != nil {
		toSerialize["file"] = o.File
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject17 struct {
	value *InlineObject17
	isSet bool
}

func (v NullableInlineObject17) Get() *InlineObject17 {
	return v.value
}

func (v *NullableInlineObject17) Set(val *InlineObject17) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject17) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject17) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject17(val *InlineObject17) *NullableInlineObject17 {
	return &NullableInlineObject17{value: val, isSet: true}
}

func (v NullableInlineObject17) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject17) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


