/*
 * Teamwork Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pmv1

import (
	"encoding/json"
)

// InlineObject101 struct for InlineObject101
type InlineObject101 struct {
	TimeEntry *ProjectsIdTimeEntriesJsonTimeEntry `json:"time-entry,omitempty"`
}

// NewInlineObject101 instantiates a new InlineObject101 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject101() *InlineObject101 {
	this := InlineObject101{}
	return &this
}

// NewInlineObject101WithDefaults instantiates a new InlineObject101 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject101WithDefaults() *InlineObject101 {
	this := InlineObject101{}
	return &this
}

// GetTimeEntry returns the TimeEntry field value if set, zero value otherwise.
func (o *InlineObject101) GetTimeEntry() ProjectsIdTimeEntriesJsonTimeEntry {
	if o == nil || o.TimeEntry == nil {
		var ret ProjectsIdTimeEntriesJsonTimeEntry
		return ret
	}
	return *o.TimeEntry
}

// GetTimeEntryOk returns a tuple with the TimeEntry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject101) GetTimeEntryOk() (*ProjectsIdTimeEntriesJsonTimeEntry, bool) {
	if o == nil || o.TimeEntry == nil {
		return nil, false
	}
	return o.TimeEntry, true
}

// HasTimeEntry returns a boolean if a field has been set.
func (o *InlineObject101) HasTimeEntry() bool {
	if o != nil && o.TimeEntry != nil {
		return true
	}

	return false
}

// SetTimeEntry gets a reference to the given ProjectsIdTimeEntriesJsonTimeEntry and assigns it to the TimeEntry field.
func (o *InlineObject101) SetTimeEntry(v ProjectsIdTimeEntriesJsonTimeEntry) {
	o.TimeEntry = &v
}

func (o InlineObject101) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TimeEntry != nil {
		toSerialize["time-entry"] = o.TimeEntry
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject101 struct {
	value *InlineObject101
	isSet bool
}

func (v NullableInlineObject101) Get() *InlineObject101 {
	return v.value
}

func (v *NullableInlineObject101) Set(val *InlineObject101) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject101) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject101) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject101(val *InlineObject101) *NullableInlineObject101 {
	return &NullableInlineObject101{value: val, isSet: true}
}

func (v NullableInlineObject101) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject101) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


