/*
 * Teamwork.com Projects API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 3.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package projv3

import (
	"encoding/json"
)

// MilestoneMilestonesResponseIncluded struct for MilestoneMilestonesResponseIncluded
type MilestoneMilestonesResponseIncluded struct {
	Companies *map[string]ViewCompany `json:"companies,omitempty"`
	Projects *map[string]ViewProject `json:"projects,omitempty"`
	Tags *map[string]ViewTag `json:"tags,omitempty"`
	Tasklists *map[string]ViewTasklist `json:"tasklists,omitempty"`
	Tasks *map[string]ViewTask `json:"tasks,omitempty"`
	Teams *map[string]ViewTeam `json:"teams,omitempty"`
	Users *map[string]ViewUser `json:"users,omitempty"`
}

// NewMilestoneMilestonesResponseIncluded instantiates a new MilestoneMilestonesResponseIncluded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMilestoneMilestonesResponseIncluded() *MilestoneMilestonesResponseIncluded {
	this := MilestoneMilestonesResponseIncluded{}
	return &this
}

// NewMilestoneMilestonesResponseIncludedWithDefaults instantiates a new MilestoneMilestonesResponseIncluded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMilestoneMilestonesResponseIncludedWithDefaults() *MilestoneMilestonesResponseIncluded {
	this := MilestoneMilestonesResponseIncluded{}
	return &this
}

// GetCompanies returns the Companies field value if set, zero value otherwise.
func (o *MilestoneMilestonesResponseIncluded) GetCompanies() map[string]ViewCompany {
	if o == nil || o.Companies == nil {
		var ret map[string]ViewCompany
		return ret
	}
	return *o.Companies
}

// GetCompaniesOk returns a tuple with the Companies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneMilestonesResponseIncluded) GetCompaniesOk() (*map[string]ViewCompany, bool) {
	if o == nil || o.Companies == nil {
		return nil, false
	}
	return o.Companies, true
}

// HasCompanies returns a boolean if a field has been set.
func (o *MilestoneMilestonesResponseIncluded) HasCompanies() bool {
	if o != nil && o.Companies != nil {
		return true
	}

	return false
}

// SetCompanies gets a reference to the given map[string]ViewCompany and assigns it to the Companies field.
func (o *MilestoneMilestonesResponseIncluded) SetCompanies(v map[string]ViewCompany) {
	o.Companies = &v
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *MilestoneMilestonesResponseIncluded) GetProjects() map[string]ViewProject {
	if o == nil || o.Projects == nil {
		var ret map[string]ViewProject
		return ret
	}
	return *o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneMilestonesResponseIncluded) GetProjectsOk() (*map[string]ViewProject, bool) {
	if o == nil || o.Projects == nil {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *MilestoneMilestonesResponseIncluded) HasProjects() bool {
	if o != nil && o.Projects != nil {
		return true
	}

	return false
}

// SetProjects gets a reference to the given map[string]ViewProject and assigns it to the Projects field.
func (o *MilestoneMilestonesResponseIncluded) SetProjects(v map[string]ViewProject) {
	o.Projects = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *MilestoneMilestonesResponseIncluded) GetTags() map[string]ViewTag {
	if o == nil || o.Tags == nil {
		var ret map[string]ViewTag
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneMilestonesResponseIncluded) GetTagsOk() (*map[string]ViewTag, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *MilestoneMilestonesResponseIncluded) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]ViewTag and assigns it to the Tags field.
func (o *MilestoneMilestonesResponseIncluded) SetTags(v map[string]ViewTag) {
	o.Tags = &v
}

// GetTasklists returns the Tasklists field value if set, zero value otherwise.
func (o *MilestoneMilestonesResponseIncluded) GetTasklists() map[string]ViewTasklist {
	if o == nil || o.Tasklists == nil {
		var ret map[string]ViewTasklist
		return ret
	}
	return *o.Tasklists
}

// GetTasklistsOk returns a tuple with the Tasklists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneMilestonesResponseIncluded) GetTasklistsOk() (*map[string]ViewTasklist, bool) {
	if o == nil || o.Tasklists == nil {
		return nil, false
	}
	return o.Tasklists, true
}

// HasTasklists returns a boolean if a field has been set.
func (o *MilestoneMilestonesResponseIncluded) HasTasklists() bool {
	if o != nil && o.Tasklists != nil {
		return true
	}

	return false
}

// SetTasklists gets a reference to the given map[string]ViewTasklist and assigns it to the Tasklists field.
func (o *MilestoneMilestonesResponseIncluded) SetTasklists(v map[string]ViewTasklist) {
	o.Tasklists = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *MilestoneMilestonesResponseIncluded) GetTasks() map[string]ViewTask {
	if o == nil || o.Tasks == nil {
		var ret map[string]ViewTask
		return ret
	}
	return *o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneMilestonesResponseIncluded) GetTasksOk() (*map[string]ViewTask, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *MilestoneMilestonesResponseIncluded) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given map[string]ViewTask and assigns it to the Tasks field.
func (o *MilestoneMilestonesResponseIncluded) SetTasks(v map[string]ViewTask) {
	o.Tasks = &v
}

// GetTeams returns the Teams field value if set, zero value otherwise.
func (o *MilestoneMilestonesResponseIncluded) GetTeams() map[string]ViewTeam {
	if o == nil || o.Teams == nil {
		var ret map[string]ViewTeam
		return ret
	}
	return *o.Teams
}

// GetTeamsOk returns a tuple with the Teams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneMilestonesResponseIncluded) GetTeamsOk() (*map[string]ViewTeam, bool) {
	if o == nil || o.Teams == nil {
		return nil, false
	}
	return o.Teams, true
}

// HasTeams returns a boolean if a field has been set.
func (o *MilestoneMilestonesResponseIncluded) HasTeams() bool {
	if o != nil && o.Teams != nil {
		return true
	}

	return false
}

// SetTeams gets a reference to the given map[string]ViewTeam and assigns it to the Teams field.
func (o *MilestoneMilestonesResponseIncluded) SetTeams(v map[string]ViewTeam) {
	o.Teams = &v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *MilestoneMilestonesResponseIncluded) GetUsers() map[string]ViewUser {
	if o == nil || o.Users == nil {
		var ret map[string]ViewUser
		return ret
	}
	return *o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneMilestonesResponseIncluded) GetUsersOk() (*map[string]ViewUser, bool) {
	if o == nil || o.Users == nil {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *MilestoneMilestonesResponseIncluded) HasUsers() bool {
	if o != nil && o.Users != nil {
		return true
	}

	return false
}

// SetUsers gets a reference to the given map[string]ViewUser and assigns it to the Users field.
func (o *MilestoneMilestonesResponseIncluded) SetUsers(v map[string]ViewUser) {
	o.Users = &v
}

func (o MilestoneMilestonesResponseIncluded) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Companies != nil {
		toSerialize["companies"] = o.Companies
	}
	if o.Projects != nil {
		toSerialize["projects"] = o.Projects
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Tasklists != nil {
		toSerialize["tasklists"] = o.Tasklists
	}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	if o.Teams != nil {
		toSerialize["teams"] = o.Teams
	}
	if o.Users != nil {
		toSerialize["users"] = o.Users
	}
	return json.Marshal(toSerialize)
}

type NullableMilestoneMilestonesResponseIncluded struct {
	value *MilestoneMilestonesResponseIncluded
	isSet bool
}

func (v NullableMilestoneMilestonesResponseIncluded) Get() *MilestoneMilestonesResponseIncluded {
	return v.value
}

func (v *NullableMilestoneMilestonesResponseIncluded) Set(val *MilestoneMilestonesResponseIncluded) {
	v.value = val
	v.isSet = true
}

func (v NullableMilestoneMilestonesResponseIncluded) IsSet() bool {
	return v.isSet
}

func (v *NullableMilestoneMilestonesResponseIncluded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMilestoneMilestonesResponseIncluded(val *MilestoneMilestonesResponseIncluded) *NullableMilestoneMilestonesResponseIncluded {
	return &NullableMilestoneMilestonesResponseIncluded{value: val, isSet: true}
}

func (v NullableMilestoneMilestonesResponseIncluded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMilestoneMilestonesResponseIncluded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


